### ISSUE TITLE
GRPC CVE affecting versions < 1.53.1

### ISSUE THREAD

**Issue by Mattwhooo** [anycable/anycable#210]
Thanks for everything you do with this library!

We are seeing security concerns raised against the version of GRPC in use by AnyCable. 

CVE-2023-32731
CVE-2023-32732
CVE-2023-1428

The recommendation in these is to update to GRPC version 1.53.1 or later and the current build is using `grpc (~> 1.37)`.    Is there an easy way to update this dependency?   Thanks again!

**Comment by palkan** [comment]
Hey!
Thanks for letting us know.

I've upgraded the requirements here: https://github.com/anycable/anycable/commit/0074511ca5f60ad983befec732980e513cf8c4d5

**Comment by Envek** [comment]
Hey @Mattwhooo, thanks for letting know.

However, as in general (and for this gem in particular) Ruby gem dependency constraints only restricts compatible _range_ versions of dependencies, but actual _exact_ dependent gem versions used in runtime are defined in every application that plugs a given Ruby gem (in application's `Gemfile.lock`).

And, as it can be hard to upgrade grpc gem sometimes (on older Rubies or older operating systems), bumping its required version without _compatibility_ issues, can affect ability of users to upgrade anycable version in the future. It is user's responsibility to update dependencies, and user may decide that it is safe to postpone upgrading grpc gem in their particular case – let them decide.

Because of this I personally tend to be against caring about security patches of a gem dependent gems, as, I believe, it should be done by gem users in application's Gemfile like this:

```ruby
# application's Gemfile
gem "anycable", "~> 1.3" # (requires grpc 1.x starting from 1.37)
gem "grpc", "~> 1.53" # (requires grpc 1.x starting from 1.53 to) fix CVE-2023-[1428,32731,32732]
```

See https://github.com/Envek/after_commit_everywhere/issues/26 for an example of somewhat similar issue and discussion in another Ruby gem.
