### ISSUE TITLE
Close broken connection

### ISSUE THREAD

**Issue by rus-max** [anycable/anycable#99]
Hi!
I want to implement [closing broken connection](https://github.com/websockets/ws#how-to-detect-and-close-broken-connections) on custom action

How to close a user connection?

**Comment by palkan** [comment]
Action Cable already has a custom ping implementation: https://docs.anycable.io/#/misc/action_cable_protocol?id=ping

It's only server->client, i.e. client could detect a broken connection.

> How to close a user connection?

Could you please elaborate: server side or client side? Ruby or anycable-go?

**Comment by rus-max** [comment]
When connect with user is lost by broken cable, user state does not change. Its installed in subscribe

```
class UserChannel
  def subscribe
    user.on!
    stream_for user
  end

  def unsubscribe
    user.off!
  end
end
```

I want to close connection from server side and set user to off

**Comment by palkan** [comment]
`#disconnect` / `#unsubscribe` callbacks are not 100% reliable, neither Action Cable nor AnyCable could guarantee them called when a socket is closed (e.g., when a server dies unexpectedly).

Instead of using an on/off state, I'd recommend tracking the `last_pinged_at` periodically and mark user as `off` if it haven't sent ping for a period of time:

```ruby
def on?
  last_pinged_at < (2*PING_INTERVAL).ago
end
``` 

And add a `ping` method to the channel and call it periodically from the client:

```ruby
def ping
  user.touch(:last_pinged_at)
end
```

**Comment by rus-max** [comment]
@palkan, thanks!
